export const executiveTeam = [
    {
      id: 1,
      name: "Mme. Oumayma OUGUENNOUS",
      image: 'src/assets/blocPhoto/prof2.jpeg',
      description: "Spécialiste des méthodologies d'apprentissage innovantes avec 15 ans d'expérience.",
      contact: 'Membre1@partners.org',
      role: "Présidente",
    },
    {
      id: 2,
      name: "Mme. Bouchra BEN AMMA",
      image: 'src/assets/blocPhoto/prof1.jpeg',
      description: "Spécialiste des méthodologies d'apprentissage innovantes avec 15 ans d'expérience.",
      contact: 'Membre2@partners.org',
      role: "Sécrétaire Générale",
    },
    {
      id: 3,
      name: "Mme. Rihab MAHDAD",
      image: 'src/assets/blocPhoto/prof3.jpeg',
      description: "Spécialiste des méthodologies d'apprentissage innovantes avec 15 ans d'expérience.",
      contact: 'Membre3@partners.org',
      role: "Trésoriere",
    },
    {
      id: 4,
      name: "Mme. Awatif BOUSSETTA",
      image: 'src/assets/blocPhoto/prof2.jpeg',
      description: "Spécialiste des méthodologies d'apprentissage innovantes avec 15 ans d'expérience.",
      contact: 'Membre1@partners.org',
      role: "Conseillere",
    },
    {
      id: 5,
      name: "Mr. Rachid ENNAJI ",
      image: 'src/assets/blocPhoto/prof1.jpeg',
      description: "Spécialiste des méthodologies d'apprentissage innovantes avec 15 ans d'expérience.",
      contact: 'Membre2@partners.org',
      role: "Conseiller",
    },
    {
      id: 6,
      name: "Mr. Rachid EL HABIB",
      image: 'src/assets/blocPhoto/prof3.jpeg',
      description: "Spécialiste des méthodologies d'apprentissage innovantes avec 15 ans d'expérience.",
      contact: 'Membre3@partners.org',
      role: "Directeur exécutif",
    },
  ];